# Generated by Django 5.1.2 on 2024-10-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_alter_sitesetup_options_sitesetup_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
    ]
